title = "My New Hugo Site"
baseurl = "http://RyoBamboo.github.io/blog"
languageCode = "ja-jp"
theme = "hyde"
canonifyurls = true

[params]
	description = "This is myblog"
	author = "my name"

[taxonomies]
	category = "categories"
	tag = "tags"


